Update bin/adock

diff --git a/bin/adock b/bin/adock
--- a/bin/adock
+++ b/bin/adock
@@ -8,130 +8,341 @@
 # named <CC0-1.0.txt>. If not, it may be available at
 # <https://creativecommons.org/publicdomain/zero/1.0/>.
 #
-# Example 1. Compile README.adoc into README.html.
-#
-#       adock README.adoc
-#
-# Example 2. Compile README.adoc into README.pdf.
-#
-#       adock -b pdf -r asciidoctor-pdf README.adoc
-#
-# Example 3. Compile README.adoc into README.html, running docker with
-# sudo.
-#
-#       DOCKER='sudo docker' adock README.adoc
-#
-# Example 4. Continuously recompile README.adoc into HTML and serve it
-# through an HTTP server listening on 0.0.0.0:8000.
-#
-#       adock --serve README.adoc
-#
-# Example 5. Pull the latest version of the quinngrier/adock Docker
-# image.
-#
-#       adock --pull
-#
 
 LC_ALL=C
 readonly LC_ALL
 export LC_ALL
 
+# :r !subset.sh gatbps_barf gatbps_parse_opt gatbps_unknown_opt
+
+#-----------------------------------------------------------------------
+# gatbps_barf
+#-----------------------------------------------------------------------
+#
+# The authors of this section have waived all copyright and
+# related or neighboring rights to the extent permitted by
+# law as described by the CC0 1.0 Universal Public Domain
+# Dedication. You should have received a copy of the full
+# dedication along with this file, typically as a file
+# named <CC0-1.0.txt>. If not, it may be available at
+# <https://creativecommons.org/publicdomain/zero/1.0/>.
+#
+
+gatbps_barf() {
+
+  case $# in 0)
+
+    printf '%s\n' "$0: Error: Unknown error." >&2
+
+  ;; 1)
+
+    printf '%s\n' "$0: Error: ${1?}" >&2
+
+  ;; *)
+
+    printf '%s' "$0: Error: ${1?}" >&2
+    shift
+    printf ' %s' "$@" >&2
+    echo >&2
+
+  esac
+
+  exit 1
+
+}
+
+#-----------------------------------------------------------------------
+# gatbps_parse_opt
+#-----------------------------------------------------------------------
+#
+# The authors of this section have waived all copyright and
+# related or neighboring rights to the extent permitted by
+# law as described by the CC0 1.0 Universal Public Domain
+# Dedication. You should have received a copy of the full
+# dedication along with this file, typically as a file
+# named <CC0-1.0.txt>. If not, it may be available at
+# <https://creativecommons.org/publicdomain/zero/1.0/>.
+#
+
+gatbps_parse_opt() {
+
+  case $# in 0)
+    gatbps_barf \
+      "gatbps_parse_opt(): At least one <option> must be given." \
+    ;
+  esac
+
+  case ${1?} in -? | --*)
+    gatbps_parse_opt_prefix=
+  ;; *)
+    gatbps_parse_opt_prefix=${1?}
+    case ${gatbps_parse_opt_prefix?} in *[!0-9A-Z_a-z]* | [0-9]*)
+      gatbps_barf \
+        "gatbps_parse_opt(): Invalid <prefix>: " \
+        "${gatbps_parse_opt_prefix?}" \
+      ;
+    esac
+    shift
+  esac
+
+  case $# in 0)
+    gatbps_barf \
+      "gatbps_parse_opt(): At least one <option> must be given." \
+    ;
+  esac
+
+  gatbps_parse_opt_opts_n=0
+  while :; do
+    case $# in 0)
+      break
+    esac
+    case ${1?} in -? | --*)
+      eval gatbps_parse_opt_opts_${gatbps_parse_opt_opts_n?}='${1?}'
+      gatbps_parse_opt_opts_n=`
+        expr ${gatbps_parse_opt_opts_n?} + 1
+      ` || exit $?
+      shift
+    ;; *)
+      break
+    esac
+  done
+
+  case ${gatbps_parse_opt_opts_n?} in 0)
+    gatbps_barf \
+      "gatbps_parse_opt(): At least one <option> must be given." \
+    ;
+  esac
+
+  case $# in 0)
+    gatbps_barf \
+      "gatbps_parse_opt(): The argument list must be given." \
+    ;
+  esac
+
+  case ${1?} in required | forbidden | permitted)
+    gatbps_parse_opt_style=${1?}
+    shift
+  ;; *)
+    gatbps_parse_opt_style=required
+  esac
+
+  case $# in 0)
+    gatbps_barf \
+      "gatbps_parse_opt(): The argument list must be given." \
+    ;
+  esac
+
+  case ${1?} in :)
+    shift
+  ;; *)
+    gatbps_barf \
+      "gatbps_parse_opt(): Unexpected argument: ${1?}" \
+    ;
+  esac
+
+  gatbps_parse_opt_opts_i=0
+
+  while :; do
+
+    case ${gatbps_parse_opt_opts_i?} in ${gatbps_parse_opt_opts_n?})
+      break
+    esac
+
+    case $# in 0)
+      break
+    esac
+
+    eval gatbps_parse_opt_opt=\$gatbps_parse_opt_opts_${gatbps_parse_opt_opts_i?}
+
+    case ${1?} in "${gatbps_parse_opt_opt?}")
+      eval ${gatbps_parse_opt_prefix?}got=:
+      eval ${gatbps_parse_opt_prefix?}opt='${gatbps_parse_opt_opt?}'
+      case ${gatbps_parse_opt_style?} in required)
+        case $# in 1)
+          gatbps_barf \
+            "Option requires an argument: ${gatbps_parse_opt_opt?}" \
+          ;
+        esac
+        eval ${gatbps_parse_opt_prefix?}arg='${2?}'
+        eval ${gatbps_parse_opt_prefix?}pop=shift
+      ;; *)
+        unset ${gatbps_parse_opt_prefix?}arg
+        eval ${gatbps_parse_opt_prefix?}pop=
+      esac
+      return
+    esac
+
+    case ${gatbps_parse_opt_opt?} in --*)
+
+      case ${1?} in "${gatbps_parse_opt_opt?}"=*)
+        case ${gatbps_parse_opt_style?} in forbidden)
+          gatbps_barf \
+            "Option forbids an argument: ${gatbps_parse_opt_opt?}" \
+          ;
+        esac
+        gatbps_parse_opt_x='
+          {
+            if (seen_equals) {
+              print;
+            } else if (/=/) {
+              seen_equals = 1;
+              sub(/[^=]*=/, "");
+              print;
+            }
+          }
+        '
+        gatbps_parse_opt_x=`eval " ${AWK:-awk}"' \
+          "${gatbps_parse_opt_x?}" \
+          <<gatbps_parse_opt_eof
+${1?}
+gatbps_parse_opt_eof
+        '` || exit $?
+        eval ${gatbps_parse_opt_prefix?}got=:
+        eval ${gatbps_parse_opt_prefix?}opt='${gatbps_parse_opt_opt?}'
+        eval ${gatbps_parse_opt_prefix?}arg='${gatbps_parse_opt_x?}'
+        eval ${gatbps_parse_opt_prefix?}pop=
+        return
+      esac
+
+    ;; *)
+
+      case ${1?} in "${gatbps_parse_opt_opt?}"*)
+        case ${gatbps_parse_opt_opt?} in '-
+')
+          gatbps_parse_opt_x='
+            1 d
+            s/'\''/&\\&&/g
+            2 s/^/'\''/
+            $ s/$/'\''/
+          '
+        ;; *)
+          gatbps_parse_opt_x='
+            1 s/^..//
+            s/'\''/&\\&&/g
+            1 s/^/'\''/
+            $ s/$/'\''/
+          '
+        esac
+        gatbps_parse_opt_x=`eval " ${SED:-sed}"' \
+          "${gatbps_parse_opt_x?}" \
+          <<gatbps_parse_opt_eof
+${1?}
+gatbps_parse_opt_eof
+        '` || exit $?
+        eval ${gatbps_parse_opt_prefix?}got=:
+        eval ${gatbps_parse_opt_prefix?}opt='${gatbps_parse_opt_opt?}'
+        case ${gatbps_parse_opt_style?} in forbidden)
+          unset ${gatbps_parse_opt_prefix?}arg
+          eval ${gatbps_parse_opt_prefix?}pop=\"'
+            shift
+            set x -${gatbps_parse_opt_x?} \"\$@\"
+          '\"
+        ;; *)
+          eval ${gatbps_parse_opt_prefix?}arg=${gatbps_parse_opt_x?}
+          eval ${gatbps_parse_opt_prefix?}pop=
+        esac
+        return
+      esac
+
+    esac
+
+    gatbps_parse_opt_opts_i=`
+      expr ${gatbps_parse_opt_opts_i?} + 1
+    ` || exit $?
+
+  done
+
+  eval ${gatbps_parse_opt_prefix?}got=false
+  unset ${gatbps_parse_opt_prefix?}opt
+  unset ${gatbps_parse_opt_prefix?}arg
+  eval ${gatbps_parse_opt_prefix?}pop=
+
+}
+
+#-----------------------------------------------------------------------
+# gatbps_unknown_opt
+#-----------------------------------------------------------------------
+#
+# The authors of this section have waived all copyright and
+# related or neighboring rights to the extent permitted by
+# law as described by the CC0 1.0 Universal Public Domain
+# Dedication. You should have received a copy of the full
+# dedication along with this file, typically as a file
+# named <CC0-1.0.txt>. If not, it may be available at
+# <https://creativecommons.org/publicdomain/zero/1.0/>.
+#
+
+gatbps_unknown_opt() {
+
+  case $# in 1)
+    :
+  ;; *)
+    gatbps_barf \
+      "gatbps_unknown_opt(): Exactly one argument must be given." \
+    ;
+  esac
+
+  case ${1?} in --*)
+
+    printf '%s' "$0: Unknown option: " >&2
+
+    sed '
+      /=/ {
+        s/=.*//
+        q
+      }
+    ' <<gatbps_unknown_opt_eof >&2
+${1?}
+gatbps_unknown_opt_eof
+
+    exit 1
+
+  ;; -?*)
+
+    printf '%s: Unknown option: %.2s\n' "$0" "${1?}" >&2
+
+    exit 1
+
+  esac
+
+}
+
+#-----------------------------------------------------------------------
+
 detach=
 unset http_addr
 image=quinngrier/adock
 unset live_addr
-unset name
-pull=false
+name=adock
+update=false
 
-# TODO: Use gatbps_parse_opt for options parsing.
+case $# in 0)
+  set x
+;; *)
+  set x "$@"
+esac
 
-while :; do
+until shift && (exit ${1+1}0); do
 
-  case ${1-} in --)
+  #---------------------------------------------------------------------
+  # --
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt -- forbidden : "$@"
+  if ${got?}; then
+    eval "${pop?}"
     shift
     break
-  esac
+  fi
 
-  case ${1-} in --detach)
-    detach=-d
-    shift
-    continue
-  esac
+  #---------------------------------------------------------------------
+  # -a, --address
+  #---------------------------------------------------------------------
 
-  case ${1-} in --image)
-    case ${2+x} in '')
-      printf '%s\n' "$0: Option requires an argument: $1" >&2
-      exit 1
-    esac
-    image=$1=$2
-    shift 2
-    case $# in 0)
-      set x "$image"
-    ;; *)
-      set x "$image" "$@"
-    esac
-    shift
-    continue
-  esac
-
-  case ${1-} in --image=*)
-    case $1 in *[!-.0-9:=A-Z_a-z]*)
-      printf '%s\n' "$0: Invalid option argument: $1" >&2
-      exit 1
-    esac
-    r='[^=]*=\(.*\)'
-    image=`expr "x$1" : "x$r"` || exit $?
-    shift
-    continue
-  esac
-
-  case ${1-} in --name)
-    case ${2+x} in '')
-      printf '%s\n' "$0: Option requires an argument: $1" >&2
-      exit 1
-    esac
-    name=$1=$2
-    shift 2
-    case $# in 0)
-      set x "$name"
-    ;; *)
-      set x "$name" "$@"
-    esac
-    shift
-    continue
-  esac
-
-  case ${1-} in --name=*)
-    case $1 in *[!-.0-9=A-Z_a-z]*)
-      printf '%s\n' "$0: Invalid option argument: $1" >&2
-      exit 1
-    esac
-    r='[^=]*=\(.*\)'
-    name=`expr "x$1" : "x$r"` || exit $?
-    shift
-    continue
-  esac
-
-  case ${1-} in --pull)
-    pull=:
-    shift
-    continue
-  esac
-
-  case ${1-} in --serve)
-    http_addr=0.0.0.0:8000
-    live_addr=0.0.0.0:35729
-    shift
-    continue
-  esac
-
-  case ${1-} in --serve=*)
-    case $1 in *[!-,.0-9:=A-Z_a-z]*)
-      printf '%s\n' "$0: Invalid option argument: $1" >&2
-      exit 1
-    esac
-    r='[^=]*=\(.*\)'
-    http_addr=`expr "x$1" : "x$r"` || exit $?
+  gatbps_parse_opt -a --address required : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    http_addr=${arg?}
     case $http_addr in *,*)
       r='.*,\(.*\)'
       live_addr=`expr "x$http_addr" : "x$r"` || exit $?
@@ -151,9 +362,71 @@ while :; do
       r='\(.*\):.*'
       live_addr=`expr "x$http_addr" : "x$r"`:$live_addr || exit $?
     esac
-    shift
     continue
-  esac
+  fi
+
+  #---------------------------------------------------------------------
+  # -d, --detach
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt -d --detach forbidden : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    detach=-d
+    continue
+  fi
+
+  #---------------------------------------------------------------------
+  # --image
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt --image required : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    image=${arg?}
+    continue
+  fi
+
+  #---------------------------------------------------------------------
+  # -n, --name
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt -n --name required : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    name=${arg?}
+    case ${name?} in '')
+      unset name
+    esac
+    continue
+  fi
+
+  #---------------------------------------------------------------------
+  # -s, --serve
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt -s --serve forbidden : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    case ${http_addr+x} in '')
+      http_addr=0.0.0.0:8000
+      live_addr=0.0.0.0:35729
+    esac
+    continue
+  fi
+
+  #---------------------------------------------------------------------
+  # -u, --update
+  #---------------------------------------------------------------------
+
+  gatbps_parse_opt -u --update forbidden : "$@"
+  if ${got?}; then
+    eval "${pop?}"
+    update=:
+    continue
+  fi
+
+  #---------------------------------------------------------------------
 
   break
 
@@ -164,15 +437,96 @@ readonly http_addr
 readonly image
 readonly live_addr
 readonly name
-readonly pull
+readonly update
+
+#-----------------------------------------------------------------------
+#
+# We want any output files produced by the container to have the
+# expected ownership. To achieve this for both rootful and rootless
+# containers, we create an empty temporary directory on the host, mount
+# it into the container, observe its ownership inside the container, and
+# replicate that ownership onto any output files. Using a temporary file
+# instead of a directory would also work, but using a directory makes it
+# easier to get an absolute path.
+#
+
+tmp_dir=`mktemp -d` || exit $?
+case ${tmp_dir?} in /*)
+  :
+;; *)
+  tmp_dir=`cd "./${tmp_dir?}" && pwd` || exit $?
+esac
+readonly tmp_dir
+
+exit_trap='
+  if command -v shred >/dev/null 2>&1; then
+    find "${tmp_dir?}" -type f -exec shred {} \; || :
+  fi
+  rm -f -r "${tmp_dir?}" || :
+'
+readonly exit_trap
+
+trap "${exit_trap?}" EXIT
+
+#-----------------------------------------------------------------------
 
 docker=${DOCKER:-docker}
 readonly docker
 
-if $pull; then
-  eval " $docker"' pull "$image"' || exit $?
-  exit
+if ${update?}; then
+
+  eval " ${docker?}"' pull -- "${image?}"' || exit $?
+
+  url=https://raw.githubusercontent.com/quinngrier/adock/master/adock
+  readonly url
+
+  if command -v curl >/dev/null 2>&1; then
+    curl -L -S -f -m 10 -s "${url?}" >"${tmp_dir?}"/adock || exit $?
+  elif command -v wget >/dev/null 2>&1; then
+    wget -O "${tmp_dir?}"/adock -T 10 "${url?}" || exit $?
+  else
+    # TODO: Use gatbps_warn.
+    printf '%s\n' "$0: Warning: Cannot download and replace adock because neither curl nor wget is installed." >&2
+    exit
+  fi
+
+  chmod +x "${tmp_dir?}"/adock || exit $?
+
+  argv0_=$0
+  readonly argv0_
+  export argv0_
+
+  exit_trap_=${exit_trap?}
+  readonly exit_trap_
+  export exit_trap_
+
+  tmp_dir_=${tmp_dir?}
+  readonly tmp_dir_
+  export tmp_dir_
+
+  exec sh -c '
+
+    argv0=${argv0_?}
+    readonly argv0
+    unset argv0_
+
+    exit_trap=${exit_trap_?}
+    readonly exit_trap
+    unset exit_trap_
+
+    tmp_dir=${tmp_dir_?}
+    readonly tmp_dir
+    unset tmp_dir_
+
+    trap "${exit_trap?}" EXIT
+
+    mv -f -- "${tmp_dir?}"/adock "${argv0?}"
+
+  '
+
 fi
+
+#-----------------------------------------------------------------------
 
 test -t 0 && s=0 || s=$?
 case $s in 0)
@@ -184,26 +538,29 @@ case $s in 0)
 esac
 readonly t
 
-u=`id -u` || exit $?
-readonly u
-
-g=`id -g` || exit $?
-readonly g
-
 pwd=`pwd` || exit $?
 readonly pwd
 
-args='run --rm -i $t $detach -u $u:$g -v "$pwd:$pwd" -w "$pwd"'
+args='run --rm -i $t $detach -v "$pwd:$pwd" -w "$pwd"'
+
+args=${args?}' -v "${tmp_dir?}":/tmp_dir'
+
+args=${args?}' -e ADOCK_UMASK='`umask` || exit $?
+
 case ${http_addr+x} in ?*)
-  args=$args' -p "$http_addr:80" -p "$live_addr:35729"'
+  args=${args?}' -p "${http_addr?}:80" -p "${live_addr?}:35729"'
 esac
+
 case ${name+x} in ?*)
-  args=$args' --name "$name"'
+  args=${args?}' --name "${name?}"'
 esac
-args=$args' "$image"'
+
+args=${args?}' "${image?}"'
+
 case ${http_addr+x} in ?*)
-  args=$args' --serve "$http_addr" "$live_addr"'
+  args=${args?}' --serve "${http_addr?}" "${live_addr?}"'
 esac
+
 readonly args
 
 case $# in 0)
